# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newCoilGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(875, 506)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.centralwidget)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.box_bfield = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_bfield.sizePolicy().hasHeightForWidth())
        self.box_bfield.setSizePolicy(sizePolicy)
        self.box_bfield.setMaximum(100)
        self.box_bfield.setProperty("value", 1)
        self.box_bfield.setObjectName(_fromUtf8("box_bfield"))
        self.gridLayout.addWidget(self.box_bfield, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.box_freq = QtGui.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_freq.sizePolicy().hasHeightForWidth())
        self.box_freq.setSizePolicy(sizePolicy)
        self.box_freq.setDecimals(1)
        self.box_freq.setMaximum(100.0)
        self.box_freq.setSingleStep(0.1)
        self.box_freq.setProperty("value", 1.0)
        self.box_freq.setObjectName(_fromUtf8("box_freq"))
        self.gridLayout.addWidget(self.box_freq, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.btn_start = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.verticalLayout.addWidget(self.btn_start)
        self.btn_stop = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop.sizePolicy().hasHeightForWidth())
        self.btn_stop.setSizePolicy(sizePolicy)
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.verticalLayout.addWidget(self.btn_stop)
        self.lcd_time = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_time.sizePolicy().hasHeightForWidth())
        self.lcd_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lcd_time.setFont(font)
        self.lcd_time.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcd_time.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcd_time.setSmallDecimalPoint(False)
        self.lcd_time.setNumDigits(8)
        self.lcd_time.setSegmentStyle(QtGui.QLCDNumber.Outline)
        self.lcd_time.setObjectName(_fromUtf8("lcd_time"))
        self.verticalLayout.addWidget(self.lcd_time)
        self.btn_close = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.verticalLayout.addWidget(self.btn_close)
        self.gridLayout_11.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.fixedDir = QtGui.QWidget()
        self.fixedDir.setObjectName(_fromUtf8("fixedDir"))
        self.gridLayout_9 = QtGui.QGridLayout(self.fixedDir)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_3 = QtGui.QGroupBox(self.fixedDir)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.x_dir = QtGui.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.x_dir.setFont(font)
        self.x_dir.setChecked(True)
        self.x_dir.setObjectName(_fromUtf8("x_dir"))
        self.gridLayout_7.addWidget(self.x_dir, 0, 0, 1, 1)
        self.y_dir = QtGui.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.y_dir.setFont(font)
        self.y_dir.setObjectName(_fromUtf8("y_dir"))
        self.gridLayout_7.addWidget(self.y_dir, 0, 1, 1, 1)
        self.z_dir = QtGui.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.z_dir.setFont(font)
        self.z_dir.setObjectName(_fromUtf8("z_dir"))
        self.gridLayout_7.addWidget(self.z_dir, 0, 2, 1, 1)
        self.neg_dir = QtGui.QCheckBox(self.groupBox_3)
        self.neg_dir.setObjectName(_fromUtf8("neg_dir"))
        self.gridLayout_7.addWidget(self.neg_dir, 1, 0, 1, 3)
        self.gridLayout_8.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.fixedDir)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.const_field = QtGui.QRadioButton(self.groupBox)
        self.const_field.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.const_field.setFont(font)
        self.const_field.setChecked(True)
        self.const_field.setObjectName(_fromUtf8("const_field"))
        self.gridLayout_4.addWidget(self.const_field, 0, 0, 1, 1)
        self.rot_field = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rot_field.setFont(font)
        self.rot_field.setObjectName(_fromUtf8("rot_field"))
        self.gridLayout_4.addWidget(self.rot_field, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fixedDir, _fromUtf8(""))
        self.freeDir = QtGui.QWidget()
        self.freeDir.setObjectName(_fromUtf8("freeDir"))
        self.gridLayout_10 = QtGui.QGridLayout(self.freeDir)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_2 = QtGui.QGroupBox(self.freeDir)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.ThetaBox = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThetaBox.sizePolicy().hasHeightForWidth())
        self.ThetaBox.setSizePolicy(sizePolicy)
        self.ThetaBox.setMaximum(180)
        self.ThetaBox.setObjectName(_fromUtf8("ThetaBox"))
        self.horizontalLayout.addWidget(self.ThetaBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.PhiBox = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PhiBox.sizePolicy().hasHeightForWidth())
        self.PhiBox.setSizePolicy(sizePolicy)
        self.PhiBox.setMaximum(360)
        self.PhiBox.setObjectName(_fromUtf8("PhiBox"))
        self.horizontalLayout_2.addWidget(self.PhiBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.freeDir, _fromUtf8(""))
        self.scriptDir = QtGui.QWidget()
        self.scriptDir.setObjectName(_fromUtf8("scriptDir"))
        self.gridLayout_12 = QtGui.QGridLayout(self.scriptDir)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QtGui.QLabel(self.scriptDir)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.npoints = QtGui.QSpinBox(self.scriptDir)
        self.npoints.setMinimum(10)
        self.npoints.setMaximum(10000)
        self.npoints.setProperty("value", 10)
        self.npoints.setObjectName(_fromUtf8("npoints"))
        self.gridLayout_6.addWidget(self.npoints, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.scriptDir)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_12.addWidget(self.label_8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.scriptDir, _fromUtf8(""))
        self.DwellScript = QtGui.QWidget()
        self.DwellScript.setObjectName(_fromUtf8("DwellScript"))
        self.formLayout_4 = QtGui.QFormLayout(self.DwellScript)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.DwellScript)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.npoints_Dwell = QtGui.QSpinBox(self.DwellScript)
        self.npoints_Dwell.setMinimum(10)
        self.npoints_Dwell.setMaximum(10000)
        self.npoints_Dwell.setProperty("value", 10)
        self.npoints_Dwell.setObjectName(_fromUtf8("npoints_Dwell"))
        self.gridLayout_3.addWidget(self.npoints_Dwell, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.DwellScript)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.dwelltime = QtGui.QDoubleSpinBox(self.DwellScript)
        self.dwelltime.setMinimum(0.1)
        self.dwelltime.setMaximum(500.0)
        self.dwelltime.setSingleStep(0.1)
        self.dwelltime.setProperty("value", 3.0)
        self.dwelltime.setObjectName(_fromUtf8("dwelltime"))
        self.gridLayout_3.addWidget(self.dwelltime, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.DwellScript)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.movetime = QtGui.QDoubleSpinBox(self.DwellScript)
        self.movetime.setMinimum(0.01)
        self.movetime.setMaximum(500.0)
        self.movetime.setSingleStep(0.1)
        self.movetime.setProperty("value", 0.5)
        self.movetime.setObjectName(_fromUtf8("movetime"))
        self.gridLayout_3.addWidget(self.movetime, 2, 1, 1, 1)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.LabelRole, self.gridLayout_3)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.calc_scripttime = QtGui.QLabel(self.DwellScript)
        self.calc_scripttime.setObjectName(_fromUtf8("calc_scripttime"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.calc_scripttime)
        self.label_12 = QtGui.QLabel(self.DwellScript)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.LabelRole, self.formLayout)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.radBut_Dwell_XY = QtGui.QRadioButton(self.DwellScript)
        self.radBut_Dwell_XY.setObjectName(_fromUtf8("radBut_Dwell_XY"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.radBut_Dwell_XY)
        self.radBut_Dwell_Sphere = QtGui.QRadioButton(self.DwellScript)
        self.radBut_Dwell_Sphere.setEnabled(True)
        self.radBut_Dwell_Sphere.setChecked(True)
        self.radBut_Dwell_Sphere.setObjectName(_fromUtf8("radBut_Dwell_Sphere"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.radBut_Dwell_Sphere)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.LabelRole, self.formLayout_3)
        self.tabWidget.addTab(self.DwellScript, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.gridLayout_11)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_status = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setAutoFillBackground(True)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_2.addWidget(self.label_status, 2, 0, 1, 1)
        self.label_field = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_field.sizePolicy().hasHeightForWidth())
        self.label_field.setSizePolicy(sizePolicy)
        self.label_field.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_field.setFont(font)
        self.label_field.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_field.setText(_fromUtf8(""))
        self.label_field.setAlignment(QtCore.Qt.AlignCenter)
        self.label_field.setObjectName(_fromUtf8("label_field"))
        self.gridLayout_2.addWidget(self.label_field, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.text_status = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_status.sizePolicy().hasHeightForWidth())
        self.text_status.setSizePolicy(sizePolicy)
        self.text_status.setObjectName(_fromUtf8("text_status"))
        self.gridLayout_2.addWidget(self.text_status, 3, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuCalibration = QtGui.QMenu(self.menubar)
        self.menuCalibration.setObjectName(_fromUtf8("menuCalibration"))
        self.menuSpherical_Coordinates = QtGui.QMenu(self.menubar)
        self.menuSpherical_Coordinates.setObjectName(_fromUtf8("menuSpherical_Coordinates"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menu_calib = QtGui.QAction(MainWindow)
        self.menu_calib.setObjectName(_fromUtf8("menu_calib"))
        self.menu_close = QtGui.QAction(MainWindow)
        self.menu_close.setObjectName(_fromUtf8("menu_close"))
        self.manue_newcalib = QtGui.QAction(MainWindow)
        self.manue_newcalib.setObjectName(_fromUtf8("manue_newcalib"))
        self.actionShow_drawing = QtGui.QAction(MainWindow)
        self.actionShow_drawing.setObjectName(_fromUtf8("actionShow_drawing"))
        self.menuFile.addAction(self.menu_close)
        self.menuCalibration.addAction(self.menu_calib)
        self.menuCalibration.addAction(self.manue_newcalib)
        self.menuSpherical_Coordinates.addAction(self.actionShow_drawing)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalibration.menuAction())
        self.menubar.addAction(self.menuSpherical_Coordinates.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.btn_start, QtCore.SIGNAL(_fromUtf8("released()")), self.label_status.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "B-Field (Gauss)", None))
        self.label_2.setText(_translate("MainWindow", "Frequency (Hz)", None))
        self.btn_start.setText(_translate("MainWindow", "Start", None))
        self.btn_stop.setText(_translate("MainWindow", "Stop", None))
        self.btn_close.setText(_translate("MainWindow", "Save Logfile and Close", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fixed direction", None))
        self.x_dir.setText(_translate("MainWindow", "X", None))
        self.y_dir.setText(_translate("MainWindow", "Y", None))
        self.z_dir.setText(_translate("MainWindow", "Z", None))
        self.neg_dir.setText(_translate("MainWindow", "Negative Direction", None))
        self.groupBox.setTitle(_translate("MainWindow", "Field mode", None))
        self.const_field.setText(_translate("MainWindow", "constant field", None))
        self.rot_field.setText(_translate("MainWindow", "rotating field", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fixedDir), _translate("MainWindow", "Fixed direction", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Free direction", None))
        self.label_3.setText(_translate("MainWindow", "q", None))
        self.label_4.setText(_translate("MainWindow", "f", None))
        self.label_5.setText(_translate("MainWindow", "only constant fields ! Frequency has no effect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.freeDir), _translate("MainWindow", "Free direction", None))
        self.label_7.setText(_translate("MainWindow", "Number of points on unit sphere", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Script for &quot;Random/Brownian Motion&quot;</span></p><p>Set the number of points being randomly <br/>distributed on a sphere with radius B. <br/>Sampling rate is specified by the frequency from below.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scriptDir), _translate("MainWindow", "Continuous Script", None))
        self.label_9.setText(_translate("MainWindow", "Number of points on unit sphere", None))
        self.label_10.setText(_translate("MainWindow", "Dwell time", None))
        self.label_11.setText(_translate("MainWindow", "Move time", None))
        self.calc_scripttime.setText(_translate("MainWindow", "0", None))
        self.label_12.setText(_translate("MainWindow", "Script length with current parameters (s)", None))
        self.radBut_Dwell_XY.setText(_translate("MainWindow", "Rotation in XY", None))
        self.radBut_Dwell_Sphere.setText(_translate("MainWindow", "Sphere script", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DwellScript), _translate("MainWindow", "Dwell Script", None))
        self.label_status.setText(_translate("MainWindow", "Status", None))
        self.label_6.setText(_translate("MainWindow", "Coil status", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuCalibration.setTitle(_translate("MainWindow", "Properties", None))
        self.menuSpherical_Coordinates.setTitle(_translate("MainWindow", "Spherical Coordinates", None))
        self.menu_calib.setText(_translate("MainWindow", "Choose calibration", None))
        self.menu_close.setText(_translate("MainWindow", "Save Log & Close", None))
        self.manue_newcalib.setText(_translate("MainWindow", "Set new calibration", None))
        self.actionShow_drawing.setText(_translate("MainWindow", "Definition", None))

import img_rc
