# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoilGUI.ui'
#
# Created: Mon Dec 05 17:13:53 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(672, 472)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.const_field = QtGui.QRadioButton(self.groupBox_2)
        self.const_field.setChecked(True)
        self.const_field.setObjectName(_fromUtf8("const_field"))
        self.verticalLayout_2.addWidget(self.const_field)
        self.rot_field = QtGui.QRadioButton(self.groupBox_2)
        self.rot_field.setObjectName(_fromUtf8("rot_field"))
        self.verticalLayout_2.addWidget(self.rot_field)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.x_dir = QtGui.QRadioButton(self.groupBox)
        self.x_dir.setChecked(True)
        self.x_dir.setObjectName(_fromUtf8("x_dir"))
        self.verticalLayout.addWidget(self.x_dir)
        self.y_dir = QtGui.QRadioButton(self.groupBox)
        self.y_dir.setObjectName(_fromUtf8("y_dir"))
        self.verticalLayout.addWidget(self.y_dir)
        self.z_dir = QtGui.QRadioButton(self.groupBox)
        self.z_dir.setObjectName(_fromUtf8("z_dir"))
        self.verticalLayout.addWidget(self.z_dir)
        self.neg_dir = QtGui.QCheckBox(self.groupBox)
        self.neg_dir.setObjectName(_fromUtf8("neg_dir"))
        self.verticalLayout.addWidget(self.neg_dir)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.box_bfield = QtGui.QSpinBox(self.centralwidget)
        self.box_bfield.setMaximum(360)
        self.box_bfield.setObjectName(_fromUtf8("box_bfield"))
        self.gridLayout.addWidget(self.box_bfield, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.box_freq = QtGui.QSpinBox(self.centralwidget)
        self.box_freq.setMaximum(360)
        self.box_freq.setObjectName(_fromUtf8("box_freq"))
        self.gridLayout.addWidget(self.box_freq, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btn_stop = QtGui.QPushButton(self.centralwidget)
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.gridLayout_3.addWidget(self.btn_stop, 1, 0, 1, 1)
        self.btn_start = QtGui.QPushButton(self.centralwidget)
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.gridLayout_3.addWidget(self.btn_start, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_status = QtGui.QLabel(self.centralwidget)
        self.label_status.setAutoFillBackground(True)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gridLayout_11.addWidget(self.label_status, 1, 0, 1, 1)
        self.text_status = QtGui.QTextBrowser(self.centralwidget)
        self.text_status.setObjectName(_fromUtf8("text_status"))
        self.gridLayout_11.addWidget(self.text_status, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_field = QtGui.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_field.setFont(font)
        self.label_field.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_field.setText(_fromUtf8(""))
        self.label_field.setAlignment(QtCore.Qt.AlignCenter)
        self.label_field.setObjectName(_fromUtf8("label_field"))
        self.gridLayout_4.addWidget(self.splitter, 1, 1, 1, 1)
        self.btn_close = QtGui.QPushButton(self.centralwidget)
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.gridLayout_4.addWidget(self.btn_close, 2, 0, 1, 1)
        self.lcd_time = QtGui.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lcd_time.setFont(font)
        self.lcd_time.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcd_time.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcd_time.setSmallDecimalPoint(False)
        self.lcd_time.setNumDigits(8)
        self.lcd_time.setSegmentStyle(QtGui.QLCDNumber.Outline)
        self.lcd_time.setObjectName(_fromUtf8("lcd_time"))
        self.gridLayout_4.addWidget(self.lcd_time, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuCalibration = QtGui.QMenu(self.menubar)
        self.menuCalibration.setObjectName(_fromUtf8("menuCalibration"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menu_calib = QtGui.QAction(MainWindow)
        self.menu_calib.setObjectName(_fromUtf8("menu_calib"))
        self.menu_close = QtGui.QAction(MainWindow)
        self.menu_close.setObjectName(_fromUtf8("menu_close"))
        self.manue_newcalib = QtGui.QAction(MainWindow)
        self.manue_newcalib.setObjectName(_fromUtf8("manue_newcalib"))
        self.menuFile.addAction(self.menu_close)
        self.menuCalibration.addAction(self.menu_calib)
        self.menuCalibration.addAction(self.manue_newcalib)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalibration.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btn_start, QtCore.SIGNAL(_fromUtf8("released()")), self.label_status.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Signal", None))
        self.const_field.setText(_translate("MainWindow", "constant field", None))
        self.rot_field.setText(_translate("MainWindow", "rotating field", None))
        self.groupBox.setTitle(_translate("MainWindow", "Direction", None))
        self.x_dir.setText(_translate("MainWindow", "x", None))
        self.y_dir.setText(_translate("MainWindow", "y", None))
        self.z_dir.setText(_translate("MainWindow", "z", None))
        self.neg_dir.setText(_translate("MainWindow", "Negative Direction", None))
        self.label.setText(_translate("MainWindow", "B-Field (Gauss)", None))
        self.label_2.setText(_translate("MainWindow", "Frequency", None))
        self.btn_stop.setText(_translate("MainWindow", "Stop", None))
        self.btn_start.setText(_translate("MainWindow", "Start", None))
        self.label_status.setText(_translate("MainWindow", "Status", None))
        self.btn_close.setText(_translate("MainWindow", "Save Logfile and Close", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuCalibration.setTitle(_translate("MainWindow", "Properties", None))
        self.menu_calib.setText(_translate("MainWindow", "Choose calibration", None))
        self.menu_close.setText(_translate("MainWindow", "Save Log and Close", None))
        self.manue_newcalib.setText(_translate("MainWindow", "Set new calibration", None))

